### PR TITLE
Issue 37 slice binding

### LINKED ISSUE #37: setWith extraArgs
Hi. Why setWith not working?
```js
setWith((_, x) => x, 'test', { test: 1 }, 2);
{ test: [Function: bound slice] }
```
Also
```js
const fn: unchanged.withHandler = (value: any, preventUpdate: boolean): any =>
  preventUpdate ? currentValue : "quz";

console.log(setWith(fn, "foo[0].bar", object)); // {foo: [{bar: 'quz'}]}
```
Print
```js
{ foo: [ { bar: 'baz' } ] }
```

### PR DESCRIPTION
**Pull request by planttheidea**
Resolves #37

### CODE REVIEW

File: src/handlers.ts [hunk 1]
```diff
@@ -14,7 +14,7 @@ import {
 } from './utils';
 
 const { isArray } = Array;
-const slice = Function.prototype.bind.call(Function.prototype.bind, Array.prototype.slice);
+const slice = Function.prototype.bind.call(Function.prototype.call, Array.prototype.slice);
```
Comment (planttheidea) [inline src/handlers.ts]: This is the fix, the first param to this `bind.call` should be `Function.prototype.call`.
